### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by valera-rozuvan** [ciferox/adone#1]
Hello! Very interesting project! What is a "hyper-fractal system"?

**Comment by maxveres** [comment]
In a general meaning, the hyperfractal system has the characteristics of fractals. You can read more at [Fractal Systems definition](http://www.fractal.org/Fractal-Systems.htm) written by Peter Fryer and Jules Ruis. Within ADONE we are trying to implement some of these concepts applied to DevOps, IoT, etc.

More details will be described later in documentation.

**Comment by valera-rozuvan** [comment]
Is this a personal project (to be used internally)? Or do you want to make it useful for a large number of people?

**Comment by maxveres** [comment]
We will use it for some of our future commercial solutions, but we hope that the project will be useful not only for us, but for the entire community.

Some of the components of ADONE are still at the design stage and by the end of this year we plan to make it as a comunity-driven project.
